# Generated by Django 4.2 on 2026-05-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='tailor_profiles/')),
                ('specialty', models.CharField(choices=[('Suits & Blazers', 'Suits & Blazers'), ('Traditional Wear', 'Traditional Wear'), ('Bridal Wear', 'Bridal Wear'), ('Casual Wear', 'Casual Wear'), ('Alterations', 'Alterations'), ('All Types', 'All Types')], default='Suits & Blazers', max_length=50)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('shop_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('working_days', models.CharField(default='Mon-Sat', max_length=100)),
                ('is_open', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='TailorCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('customer_measurements', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='customer_profiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tailor.tailor')),
            ],
        ),
        migrations.CreateModel(
            name='TailorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('garment_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Completed', 'Completed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=10)),
                ('delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tailor.tailorcustomer')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tailor.tailor')),
            ],
        ),
        migrations.CreateModel(
            name='TailorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tailor.tailorcustomer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tailor.tailororder')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tailor.tailor')),
            ],
        ),
        migrations.CreateModel(
            name='TailorMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('hip', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('inseam', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bicep', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('thigh', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('calf', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('measurement_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_records', to='tailor.tailorcustomer')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_records', to='tailor.tailor')),
            ],
        ),
    ]
